### PR TITLE
Add Player::OnQuestComplete()

### PR DESCRIPTION
**Pull request by BuildingOutLoud**
Here is a hook attached to the player completing a quest. I chose event number 43 as it was the next in line. I am not sure if there is a more solid methodology. :)

local function OnQuestComplete(event, player, creature, quest)
    print(player:GetName().." completed quest "..quest:GetId())
end
RegisterPlayerEvent(43, questItemTest.OnQuestComplete)

prints on AC: Theboss completed quest 7803

### CODE REVIEW

**Comment by BuildingOutLoud** [comment]
Hiya, should I submit a PR to azerothcore, or is there something that needs to be changed on these two hook PR's?

I am unsure how cross project PR's work. :)

**Comment by xIvan0ff** [comment]
@Rochet2 Merge? What do you think.

**Comment by Rochet2** [comment]
Hooks are a bit problematic as they need to be added server-side to different cores. I guess I would hope to change this in the future.
Otherwise, I think the code looks alright.

**Comment by Foereaper** [comment]
This has now been added as Player event 54, OnQuestStatusChanged. You can check the status for QUEST_STATUS_COMPLETE       = 1

**Pull request closed without merging**
