### PR TITLE
Eluna Module Update

### PR DESCRIPTION
**Pull request by Meltie2013**
Update Eluna to match this PR https://github.com/mangoszero/server/pull/157

### CODE REVIEW

**Comment by billy1arm** [comment]
@Rochet2 This PR also requires an change to the RealmD submodule (which is actually dependant on this change)

See https://github.com/mangoszero/server/pull/157

**Comment by Rochet2** [comment]
Once TC and AC builds pass, just say when to merge.

**Comment by Rochet2** [comment]
Are the changes going to be on all mangos versions (one, two...)?

**Comment by Meltie2013** [comment]
I believe it's going to be ported to all the versions after the original PR.
At the moment looking at why Mangos is failed with Linux and not Windows.

This should be valid on both side.
```cpp
Utf8ToUpperOnlyLatin
```

**Comment by Rochet2** [comment]
Btw. note that the code has "if **not** defined azerothcore".
You probably want to revert that change in the code for the accountmgr and instead change this https://github.com/ElunaLuaEngine/Eluna/blob/8f5c4699b2531c408b615f55270541a7267c742b/ElunaIncludes.h#L135
into just sAccountMgr without the &.

**Comment by Meltie2013** [comment]
@Rochet2 I should have it reverted soon.

**Comment by Foereaper** [comment]
This pr is no longer relevant, so closing.

**Pull request closed without merging**
