### PR TITLE
Implement instance scripting system.

### PR DESCRIPTION
**Pull request by Patman64**
Now you can add scripts to instances and be able to store persistent data for the instance!

The data table is passed in to all Map/instance hooks. It is a standard Lua table that is shared between calls (if you apply a metatable on initialize it will still be there on subsequent hook calls).

It contains a special field, `map`, which is always guaranteed to be a valid `Map` reference.

You can also access the instance data from any `Map` instance using the `Map:GetInstanceData` method. It will return `nil` if the `Map` does not have a script supplied by Eluna.

The data table must be manually saved with the `Map:SaveInstanceData` method.

**Notes:**
- The instance data table is encoded first with `lmarshal`, then with Base-64, and is persisted using the same system in mangos that SD2 uses.
- ~~**No Trinity support yet!** Rochet will have to do this.~~

**Example script:**
Try this script on ElunaMangosClassic!
- Enter the Deadmines and save your character.
- Note the magic number printed to the console.
- Now use `.reload eluna` or restart mangos.
- When you enter the Deadmines again it will print the magic number from before!
- (I know, kinda lame, but you get the picture.)
```lua
function OnLoad(event, data)
	print("[LOAD] Loaded successfully, magic number is: " .. (data.magic_number or 'nil'))

	local magic_number = math.random(1e3)
	print("[LOAD] New magic number is: " .. magic_number)
	print("")

	data.magic_number = magic_number
	data.map:SaveInstanceData()
end

function OnInitialize(event, data)
	math.randomseed(os.time())

	local magic_number = math.random(1e3)
	print("")
	print("[INIT] Magic number is: " .. magic_number)

	data.magic_number = magic_number
	data.map:SaveInstanceData()
end

function OnUpdate(event, data)
	-- This is only here so that when you run `.reload eluna`,
	--   the update hook triggers reloading of the instance data into Eluna.
end

RegisterMapEvent(36, InstanceEvents.LOAD, OnLoad)
RegisterMapEvent(36, InstanceEvents.INITIALIZE, OnInitialize)
RegisterMapEvent(36, InstanceEvents.UPDATE, OnUpdate)
```

### CODE REVIEW

**Comment by Rochet2** [comment]
> The data table must be manually saved with the Map:SaveInstanceData method.

The normal C++ scripts dont seem to have this (normally, its a special case). Pretty sure we shouldnt need to do that either.
However the reloading does impose a problem when the data is changed and not yet saved and the lua data is lost. Thus the changed unsaved data is lost.
The solution would be to on reload before closing to save all instance data we have.

I checked the code and asked a bit around and it seems any instance can be identified solely by the instanceID. There is no need for the mapID if instanceID is not 0 and the other way around.
So the instance ID registering seems fine and we could also make the creature registering take advantage of that as well.

However instanceIDs are freed and reused on runtime (on both TC and mangos). The current code doesnt have anything adressing this, so HasInstanceData will return true even if it should be false and after freeing the instanceID, the code still preserves the data and references for the table etc.

We could try hold the reference in the instance script and when the object gets destroyed, remove it from lua if lua exists. (unref)

**Comment by Rochet2** [comment]
Core changes for TC
```diff
diff --git a/src/LuaEngine b/src/LuaEngine
index 32e7a5e..6ef7dec 160000
--- a/src/LuaEngine
+++ b/src/LuaEngine
@@ -1 +1 @@
-Subproject commit 32e7a5e065cf2e2bfd8d5b6fccd87108dfcfe235
+Subproject commit 6ef7decbfb753cf587caef3cc70f0da66cf38df2
diff --git a/src/server/game/Maps/MapManager.cpp b/src/server/game/Maps/MapManager.cpp
index 1d01eec..952127e 100644
--- a/src/server/game/Maps/MapManager.cpp
+++ b/src/server/game/Maps/MapManager.cpp
@@ -37,6 +37,9 @@
 #include "WorldSession.h"
 #include "Opcodes.h"
 #include "AchievementMgr.h"
+#ifdef ELUNA
+#include "LuaEngine.h"
+#endif
 
 MapManager::MapManager()
 {
@@ -404,4 +407,8 @@ void MapManager::FreeInstanceId(uint32 instanceId)
 
     _instanceIds[instanceId] = false;
     sAchievementMgr->OnInstanceDestroyed(instanceId);
+
+#ifdef ELUNA
+    sEluna->FreeInstanceId(instanceId);
+#endif
 }
diff --git a/src/server/game/Scripting/ScriptMgr.cpp b/src/server/game/Scripting/ScriptMgr.cpp
index 9f841db..104f273 100644
--- a/src/server/game/Scripting/ScriptMgr.cpp
+++ b/src/server/game/Scripting/ScriptMgr.cpp
@@ -722,6 +722,10 @@ void ScriptMgr::OnMapUpdate(Map* map, uint32 diff)
 InstanceScript* ScriptMgr::CreateInstanceData(InstanceMap* map)
 {
     ASSERT(map);
+#ifdef ELUNA
+    if (InstanceScript* script = sEluna->GetInstanceData(map))
+        return script;
+#endif
 
     GET_SCRIPT_RET(InstanceMapScript, map->GetScriptId(), tmpscript, NULL);
     return tmpscript->GetInstanceScript(map);
```

**Comment by Patman64** [comment]
I've changed the behavior of `SaveInstanceData`: **calling it in Initialize does nothing if Load is going to be called afterward**, so that the data being loaded isn't overwritten.

Script authors will also need to be aware that **any data stored in Initialize will get overwritten if Load is called afterward**.

Try it with this script:
```lua
function OnLoad(event, data)
	print("[LOAD] Loaded successfully, magic number was: " .. data.magic_number)

	local magic_number = math.random(1e3)
	print("[LOAD] New magic number is: " .. magic_number)
	print("")

	data.magic_number = magic_number
	data.map:SaveInstanceData()
end

function OnInitialize(event, data)
	math.randomseed(os.time())

	local magic_number = math.random(1e3)
	print("")
	print("[INIT] Magic number is: " .. magic_number)

	data.magic_number = magic_number
	data.map:SaveInstanceData()
end

function OnUpdate(event, data)
	-- This is only here so that when you run `.reload eluna`,
	--   the update hook triggers reloading of the instance data into Eluna.
end

RegisterMapEvent(36, InstanceEvents.LOAD, OnLoad)
RegisterMapEvent(36, InstanceEvents.INITIALIZE, OnInitialize)
RegisterMapEvent(36, InstanceEvents.UPDATE, OnUpdate)
```

You should get results like so:

eluna_instance_test

**Comment by Patman64** [comment]
OK, so I recently did a bit more work on this.

I've realized that the best way to have this working is to make `Initialize` and `Load` mutually exclusive: either `Initialize` is called, or `Load` is called, but *never both*. This means that the Trinity code will have to be changed.

This resolves one of the difficulties, which was saving during loading. **It's now completely safe to save in the code that gets called on load.**

It also makes it a lot simpler for script authors to reason about, since they will have **one piece of code that is called once (ever)** and **one piece of code that is called on every reload**.

**Comment by Patman64** [comment]
Continued in https://github.com/ElunaLuaEngine/Eluna/pull/153.

**Pull request closed without merging**
