### PR TITLE
Add SendVendorWindow

### PR DESCRIPTION
**Pull request by illunix**

### CODE REVIEW

**Comment by Foereaper** [comment]
What emulators has this been tested with? Please make sure to add proper defines for what emulator it works with to prevent compile errors for others.

**Comment by illunix** [comment]
I've tested it on TC and AC, defines is same for both emulators @Foereaper

**Comment by Foereaper** [comment]
What does this do differently to Player:SendListInventory? From what I can tell this is what you want to achieve?

**Comment by Rochet2** [comment]
CI was added and it shows that the build fails for all other cores except AC.
It seems that the code requires multivendor, which is not present on other cores.

**Comment by illunix** [comment]
Alrighty then I will edit it and this method will be only available for AC @Rochet2

**Comment by Rochet2** [comment]
The changes could probably be merged with the SendListInventory function that Foereaper mentions.

**Comment by illunix** [comment]
Idk what you mean

**Comment by Rochet2** [comment]
https://github.com/ElunaLuaEngine/Eluna/blob/a22fdc639a1964b39379e738e9776c33fe8b0d4e/PlayerMethods.h#L2350-L2356

```cpp
    int SendVendorWindow(lua_State* L, Player* player)
    {
        Unit* sendTo = sEluna->CHECKOBJ<Unit>(L, 2);
        uint32 creatureEntry = Eluna::CHECKVAL<uint32>(L, 3);
        player->GetSession()->SendListInventory(sendTo->GET_GUID(), creatureEntry);
        return 0;
    }
```

If you compare the existing code and your code, there is only one difference.
Instead of making an entirely new function you can add the small change to the existing function.

**Pull request closed without merging**
