### PR TITLE
Rework Eluna's bindings

### PR DESCRIPTION
**Pull request by Patman64**
Well that was a fun 3 days of copy-and-pasting snippets. XD

I've unified all of the different Bindings into a single class (`BindingMap`). This, in turn, simplifies some of the helper functions (since they only need to operate on one type of binding) and makes the code quite a bit cleaner.

### CODE REVIEW

**Comment by Patman64** [comment]
It doesn't build on Linux yet because I have yet to figure out how to get it to compile in C++11 mode.

**Comment by Rochet2** [comment]
The recursive part of the mutex is no longer needed?
Since above all it should be a read write mutex and recursion doesnt fit with that.

**Comment by Patman64** [comment]
@Rochet2 Yup, doesn't need to be recursive any more. All the changes look good.

**Comment by Rochet2** [comment]
- [ ] Possibly add another hashmap or something to speed up remove() operation which is terribly slow with large amounts of bindings. For example removing 3000 bindings takes 55 ms and with hashmap takes 1ms.

- [ ] Add c++11 compiling flags to core side for unix compilers. Seems VS 2010+ handles the code allright.

**Comment by Rochet2** [comment]
The required core changes for mangos and cmangos:
https://github.com/Rochet2/ElunaMangosWotlk/commit/6194ddb43c6771deab79c665642272fcaebeebbd

**Pull request closed without merging**
