### PR TITLE
mutex on eluna engine

### PR DESCRIPTION
**Pull request by claudiodfc**
This PR must be merged at the same time as https://github.com/azerothcore/azerothcore-wotlk/pull/4821

Since Winfin changes the `ObjectAccessor.h` file, this PR will fail on the build since I didn't change the necessary files on the server source to avoid conflicts. Therefore, to merge that PR this one has to follow or the other way around and re-launch the git build jobs to test it!

### CODE REVIEW

**Comment by claudiodfc** [comment]
Compiling that PR with this PR results on build successful:

image

**Comment by Rochet2** [comment]
Hmm. I see TC and AC cases are merged together. But what about the else case? Was there a reason to remove it?

**Comment by claudiodfc** [comment]
Is the Eluna engine used by any other cores? I thought only AC and TC used it 🤔

**Comment by Rochet2** [comment]
Over the years support has been added for mangos and cmangos. However, cmangos has not been kept updated.

**Comment by Rochet2** [comment]
Seems there are two PRs for the same thing.
https://github.com/ElunaLuaEngine/Eluna/pull/348/files

Both do almost identical changes. Currently, the other one is closer to what is needed as it has correct whitespace and no unnecessary include.

**Pull request closed without merging**
