### PR TITLE
feat(GlobalMethods/AzerothCore): switch to new threading system

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
## Changes
- Switch to new threading system
- Part https://github.com/azerothcore/azerothcore-wotlk/pull/4821

### CODE REVIEW

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
@Rochet2 can you please have a look at this?

**Comment by Winfidonarleyan** [comment]
> @Rochet2 can you please have a look at this?

https://github.com/ElunaLuaEngine/Eluna/pull/349#issuecomment-803083238

**Comment by Rochet2** [comment]
It's ready for merge. Just tell when it's needed.

**Comment by FrancescoBorzi** [comment]
@Rochet2 should be ready now, please restart the build and it should pass now

**Pull request merged**
