### PR TITLE
Allow scripting of instances w/ persistent data

### PR DESCRIPTION
**Pull request by Patman64**
This is a continuation of https://github.com/ElunaLuaEngine/Eluna/pull/146. I've squashed the commits and rebased it onto the latest master (including new bindings).

**Trinity Note:** Some special handling in the core is needed for https://github.com/ElunaLuaEngine/Eluna/commit/9a0ae26b577854f3ebf925818d78c84e4f3322d4, since either `Initialize` or `Load` is expected to be called for an instance, but never both.

### CODE REVIEW

**Comment by Rochet2** [comment]
Only last commit is related to this PR. Rest is from merge.

**Comment by Patman64** [comment]
Made the change I wanted to. Tested and works. :+1: 

This PR should be ready to merge.

**Comment by Rochet2** [comment]
Ill merge tomorrow sadly.
Dont want to screw things up at 4 am.

**Comment by Rochet2** [comment]
Hmm, currently we are not serializing the guid data since it is userdata.
Users will have to keep using uint32 guid and constructing the guids from those with the entry using http://eluna.emudevs.com/Global/GetUnitGUID.html and similar

**Comment by Rochet2** [comment]
Having crash with
```lua
local Point = { }
function Point:new(x, y)
   self.__index = self
   return setmetatable({ x = x, y = y }, self)
end
function Point:move(x, y)
   self.x = x
   self.y = y
end
function Point:__persist()
   local x = self.x
   local y = self.y
   return function()
      -- do NOT refer to self in this scope
      return setmetatable({ x = x, y = y }, Point)
   end
end

function OnLoad(event, data, map)
    print("[LOAD] Loaded successfully, magic number is: " .. (data.magic_number or 'nil'))
    print("[LOAD] Loaded successfully, X is: " .. (data.TEST.x or 'nil'))
    print("[LOAD] Loaded successfully, Y is: " .. (data.TEST.y or 'nil'))
    data.TEST:move(7, 8)
    print("[LOAD] Loaded successfully, X is: " .. (data.TEST.x or 'nil'))
    print("[LOAD] Loaded successfully, Y is: " .. (data.TEST.y or 'nil'))

    local magic_number = math.random(1e3)
    print("[LOAD] New magic number is: " .. magic_number)
    print("")

    data.magic_number = magic_number
    data.TEST = Point:new(50, 40)
    map:SaveInstanceData()
end

function OnInitialize(event, data, map)
    local magic_number = math.random(1e3)
    print("")
    print("[INIT] Magic number is: " .. magic_number)

    data.magic_number = magic_number
    data.TEST = Point:new(50, 40)
    map:SaveInstanceData()
end

RegisterMapEvent(36, 1, OnInitialize)
RegisterMapEvent(36, 2, OnLoad)
RegisterMapEvent(36, 3, function() end)

```

**Comment by Rochet2** [comment]
Tried fixing __persist method implementation but seems it doesnt work or then the issue is somewhere else.
https://gist.github.com/Rochet2/89e1448b94e238847fe0

**Comment by Rochet2** [comment]
Seems to work fine now.

**Comment by Rochet2** [comment]
merged https://github.com/ElunaLuaEngine/Eluna/commit/31470c2cf7b9724ce0d1267c38d2d2c5e6f2ca7b

Also reminder for mangos based changes:
https://github.com/ElunaLuaEngine/ElunaMangosClassic/tree/instance_scripts

**Pull request closed without merging**
