### PR TITLE
Compatible with SUNWELLCORE

### PR DESCRIPTION
**Pull request by AyaseCore**
Compatible with SUNWELLCORE.
My current core is SunwellCore.
If I have time, I will change it to azerothCore.

 SharedDefines.h
```
#ifdef ELUNA
//#define TRINITY 
#define SUNWELL
#define WOTLK
#endif
```

The cmakelist.txt file needs to change the project name.
I forgot to correct it.

The last.Thank the eluna team for bringing us this lua engine.

i'm so sorry. my english is poor.

### CODE REVIEW

**Comment by diegobfl** [comment]
@AyaseCore
our is incredible this, dear friend could upgrade this system Lua to current AzerothCore, we are working with much dedication and with the implemented system eluna would be perfect.

**Comment by BarbzYHOOL** [comment]
Why are you on sunwellcore Ayase?

**Comment by AyaseCore** [comment]
@BarbzYHOOL 
Because I was already using Sunwellcore when the Azerothcore didn't appear.

A lot of changes have been made to sunwellcore, and it's a hassle to merge with azerothcore.

And I'm lazy. So I've been using sunwellcore.

**Comment by Viste** [comment]
@AyaseCore agree with you position to Azeroth. But tell me waht about stability and performance after adding eluna to sunwell

**Comment by AyaseCore** [comment]
I didn't test it, but I think it would have an impact on performance, because eluna is single-threaded.
```
#if ELUNA
    if (num_threads > 1)
    {
        // Force 1 thread for Eluna as lua is single threaded. By default thread count is 1
        // This should allow us not to use mutex locks
        TC_LOG_ERROR("maps", "Map update threads set to %i, when Eluna only allows 1, changing to 1", num_threads);
        num_threads = 1;
    }
#endif
```

**Comment by Viste** [comment]
@AyaseCore i try add you PR to my sunwell and send you reports about all

**Comment by Viste** [comment]
in few days

**Comment by Rochet2** [comment]
About the thread limitation, mutex locks have since been implemented.
Some people have been running Eluna with multiple threads enabled (removed the limitation) and some issues related to that have been fixed (https://github.com/ElunaLuaEngine/Eluna/commit/476cdcd2c372e30b60a61974726096418ec7cd08).
One performance issue was also resolved very recently in https://github.com/ElunaLuaEngine/Eluna/commit/00ba8e518ccd73e1404c524d9b0f982fb541c14d.
If someone has performance issues, it would be great to have hints or reports about what exactly is the problem.
If you want to try boost performance, you can try remove the thread limitation.

If there are instabilities use ThreadSanitizer or helgrind to get reports.
If there are performance isues use VS profiling tools or linux equivalents (perf, gprof) to get reports.

**Comment by Viste** [comment]
@Rochet2 allways send reports but official work on shared and VPS hosting eat a lot of my time, so all reports and test i can do only next month

**Comment by AyaseCore** [comment]
Dear friends, thank you. Last night I finished azerothcore with eluna.
If you can, take a look and see if there is any need to change.
@Rochet2 @Viste @BarbzYHOOL 

The eluna Settings file is not added to the mod. It will be added later.
```
###################################################################################################
#  ELUNA SETTINGS
#
#   Eluna.Enabled
#       Description: Enable or disable Eluna LuaEngine
#       Default:    true  - (enabled)
#                   false - (disabled)
#
#   Eluna.TraceBack
#       Description: Sets whether to use debug.traceback function on a lua error or not.
#                    Notice that you can redefine the function.
#       Default:    false - (use default error output)
#                   true  - (use debug.traceback function)
#
#   Eluna.ScriptPath
#       Description: Sets the location of the script folder to load scripts from
#                    The path can be relative or absolute.
#       Default:    "lua_scripts"
#

Eluna.Enabled = true
Eluna.TraceBack = false
Eluna.ScriptPath = "lua_scripts"
```

I'm not sure if the hook is correct:
src\server\game\Maps\MapInstanced.cpp
```
#ifdef ELUNA
    sEluna->FreeInstanceId(instanceId);
#endif
```

Eluna API changes:
OnConfigLoad(bool reload) => OnConfigLoad(bool reload, bool isBefore)

If want to remove  single-thread limit just get rid of this code? @Rochet2 
The current branch has merged The latest submission of The main branch.
src\server\game\Maps\MapManager.cpp
```
#ifdef ELUNA
    if (num_threads > 1)
    {
        // Force 1 thread for Eluna as lua is single threaded. By default thread count is 1
        // This should allow us not to use mutex locks
        ELUNA_LOG_ERROR("MAP:Map update threads set to %i, when Eluna only allows 1, changing to 1", num_threads);
        num_threads = 1;
    }
#endif
```

azerothcore:https://github.com/AyaseCore/azerothcore-wotlk/tree/ElunaAzerothWotlk
eluna:https://github.com/AyaseCore/Eluna/tree/ElunaAzerothWotlk
azerothcore-module:https://github.com/AyaseCore/mod-LuaEngine

**Comment by Rochet2** [comment]
> If want to remove single-thread limit just get rid of this code?

yes

> I'm not sure if the hook is correct:

looks fine

**Comment by AyaseCore** [comment]
Thank you for your answer @Rochet2  :)

**Comment by AyaseCore** [comment]
If I finished the azerothcore module, allowing published to the http://www.azerothcore.org/modules-catalogue/? @Rochet2

**Comment by BarbzYHOOL** [comment]
Are you in our discord Ayase? Has it been tested? And yes, we will publish it !

**Comment by AyaseCore** [comment]
I tested some lua scripts that I wrote. I can run normally. But eluna has a lot of hooks. I didn't test all of the hooks. @BarbzYHOOL

**Comment by AyaseCore** [comment]
I know there's a lot to change, because I'm just an amateur. 
Although it can now run normally.But I change is not the best. 
Because eluna support trinity, mangos, But no azeroth. 
So I try to add to the azerothcore. 
Because I believe that many friends and I am hoping to use eluna in the azerothcore.

Hope later eluna can support trinity, mangos, cmangos and azeroth.
@Rochet2

**Pull request closed without merging**
