### PR TITLE
New player event: PLAYER_EVENT_ON_PET_ADDED_TO_WORLD

### PR DESCRIPTION
**Pull request by UltraNix**

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
@Rochet2 can you please merge this PR?

**Comment by 55Honey** [comment]
Tested with https://github.com/55Honey/Acore_ZoneDebuff/pull/2
Works as intended including pets and minions.

**Comment by 55Honey** [comment]
Matching PR to fix build exists on AC.

**Comment by yuanf225** [comment]
Currently the AC+eluna module cannot be compiled

**Comment by 55Honey** [comment]
> Currently the AC+eluna module cannot be compiled

@yuanf225  You should, open a new issue about it on and AC repo because it is not related to this PR. The matching PR on AC is not merged yet.

**Comment by Helias** [comment]
@Rochet2 what about merging it?

**Comment by yuanf225** [comment]
@Rochet2 what about merging it?

**Comment by 55Honey** [comment]
Included in #393

**Comment by Rochet2** [comment]
New hooks are not likely to be added at this time as they require core changes.
New hooks may be added if they document the core they work on

**Pull request closed without merging**
